package javaprojeodevi;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author UTKU
 */
public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    /*private static final long serialVersionUID = 1L;
    
    public MainFrame(){
        super();
        this.setTitle();
        this.setUndecorated(true);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }*/
    public AnaSayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIslemler = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        lblKelimeUygulamasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ana Sayfa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnIslemler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIslemler.setText("Kelime İşlemleri");
        btnIslemler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIslemlerActionPerformed(evt);
            }
        });

        btnList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnList.setText("Kelimeleri Listele");
        btnList.setPreferredSize(new java.awt.Dimension(75, 32));
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnTest.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTest.setText("Test");
        btnTest.setPreferredSize(new java.awt.Dimension(75, 32));

        lblKelimeUygulamasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKelimeUygulamasi.setText("Kelime Uygulaması");
        lblKelimeUygulamasi.setPreferredSize(new java.awt.Dimension(236, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(lblKelimeUygulamasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblKelimeUygulamasi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnIslemler)
                .addGap(56, 56, 56)
                .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIslemlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIslemlerActionPerformed
        close();
        KelimeIslemleriSayfasi sayfa2 = new KelimeIslemleriSayfasi();
        sayfa2.setVisible(true);
    }//GEN-LAST:event_btnIslemlerActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        close();
        KelimeListeleSayfasi sayfa4 = new KelimeListeleSayfasi();
        sayfa4.setVisible(true);
    }//GEN-LAST:event_btnListActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void init() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIslemler;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel lblKelimeUygulamasi;
    // End of variables declaration//GEN-END:variables

}
